# CSS Styles from Pandas HW
styles = [
    dict(selector='th', props=[('font-family', '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'),
                               ('font-size', '1.25rem'),
                               ('border-collapse', 'collapse'),
                               ('border-spacing','0'),
                               ('color', '#2e2e2e'),
                               ('box-sizing', 'border-box'),
                               ('text-align', 'left'),
                               ('border', '1px solid #dfdfdf'),
                               ('padding', '10px 16px'),
                               ('line-height', '20px'),
                               ('vertical-align', 'middle'),
                               ('background-color', '#fafafa'),
                               ('font-weight', '400'),
                               ('border-bottom', 'solid 2px #ccc')]),
    dict(selector='td', props=[('font-family',  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'),
                               ('font-size', '1.25rem'),
                               ('font-weight',  '400'),
                               ('text-align',  'left'),
                               ('border-collapse',  'collapse'),
                               ('border-spacing',  '0'),
                               ('color',  '#2e2e2e'),
                               ('box-sizing',  'border-box'),
                               ('border',  '1px solid #dfdfdf'),
                               ('padding',  '10px 16px'),
                               ('line-height',  '20px'),
                               ('vertical-align',  'middle'),
                               ('background-color', '#ffffff'),
                               ('border-color',  '#dfdfdf')])]